const pontos = [
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "desktop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "desktop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "desktop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "desktop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "desktop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "desktop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "desktop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "desktop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "desktop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "desktop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "desktop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "desktop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "desktop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "desktop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "desktop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "desktop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "desktop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "desktop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "desktop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "desktop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "desktop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "desktop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "desktop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "laptop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "laptop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
  {
    horario: "14/08/2023 18:42:14",
    aparelho: "laptop",
    canal: "navegador",
    modo: "Individual",
    comentario: "saída",
    comprovante: "Indiponivel",
  },
];

export default pontos;
